[settings]
strict = true
verbose = true
doctype = "<!DOCTYPE html>"
clean_urls = false
page_file_extensions = ["htm", "html", "md"]
ignore_extensions = ["draft"]
plugin_discovery = true
plugin_dirs = ["scripts/plugins"]

default_template_file = "templates/main.html"
default_content_selector = "article"
default_content_action = "append_child"

[preprocessors]
md = 'pandoc -f commonmark+smart -t html --no-highlight'

[widgets.header]
widget = "include"
selector = "header"
file = "templates/header.html"

[widgets.menu-inner]
widget = "exec"
selector = ["#gen-menu"]
command = "pandoc -f commonmark+smart -t html --no-highlight templates/menu.md"

[widgets.generator-meta]
widget = 'insert_html'
selector = 'head'
html = '<meta name="generator" content="soupault">'

[widgets.page-title]
widget = "title"
selector = "h1"
default = "Project Unison"
append = " | Project Unison"
force = true
keep = true

[widgets.table-of-contents]
widget = "toc"
selector = "#gen-toc"

min_level = 2
max_level = 3
toc_list_class = "toc"
numbered_list = false
heading_links = true
heading_link_text = "ยง"
heading_link_class = "section"
use_heading_slug = true
