[config]
title = "Project Unison"
path = "Web SRD Files"

[entry]
name = "Project Unison Web SRD"
path = "Web SRD Files/ch1-meta/title.html"

[fonts]
main = "templates/fonts/MPLUS2-VariableFont_wght.ttf"
title = "templates/fonts/MPLUSRounded1c-Bold.ttf"
code = "templates/fonts/NotoSansMono-VariableFont_wdth,wght.ttf"
symbol = "templates/fonts/HachiMaruPop-Regular.ttf"

code_fallback = ["main"]